version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: brainly-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: brainly
      POSTGRES_PASSWORD: brainly123
      POSTGRES_DB: brainly
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
